# Generated by Django 6.0.6 on 2026-07-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=20)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='admission/photos/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='admission/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.session')),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.bloodgroup')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.studentclass')),
            ],
        ),
    ]
