# Generated by Django 6.0.6 on 2026-07-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_alter_subjectassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='subjects.subjectassignment')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
