# Generated by Django 6.0.6 on 2026-08-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['day', 'period__number']},
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_time',
        ),
        migrations.AddField(
            model_name='routine',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='routine.period'),
        ),
    ]
