# Generated by Django 6.0.6 on 2026-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_period_alter_routine_options_remove_routine_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='routine',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
