# Generated by Django 6.0.6 on 2026-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our School', max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/about/')),
                ('button_text', models.CharField(default='Read More', max_length=100)),
                ('button_url', models.CharField(default='/about/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
