# Generated by Django 6.0.6 on 2026-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Science', 'Science'), ('Business Studies', 'Business Studies'), ('Humanities', 'Humanities')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Head Teacher', 'Head Teacher'), ('Assistant Head Teacher', 'Assistant Head Teacher'), ('Senior Teacher', 'Senior Teacher'), ('Assistant Teacher', 'Assistant Teacher')], max_length=30),
        ),
    ]
