# Generated by Django 6.0.6 on 2026-07-11 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Office Superintendent', 'Office Superintendent'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Office Assistant', 'Office Assistant'), ('Computer Operator', 'Computer Operator'), ('Store Keeper', 'Store Keeper'), ('Library Assistant', 'Library Assistant'), ('Lab Assistant', 'Lab Assistant'), ('Lab Attendant', 'Lab Attendant'), ('Driver', 'Driver'), ('Security Guard', 'Security Guard'), ('Office Support Staff', 'Office Support Staff'), ('Cleaner', 'Cleaner')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number.', regex='^01[3-9]\\d{8}$')])),
                ('dob', models.DateField()),
                ('joining_date', models.DateField()),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
            ],
        ),
    ]
