# Generated by Django 6.0.6 on 2026-07-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('subjects', '0003_subjectassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectassignment',
            options={'ordering': ['subject']},
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentclass'),
        ),
    ]
