# Generated by Django 6.0.6 on 2026-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0001_initial'),
        ('subjects', '0005_alter_subject_name'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subjectassignment',
            constraint=models.UniqueConstraint(fields=('subject', 'student_class', 'section'), name='unique_subject_class_section_assignment'),
        ),
    ]
