# Generated by Django 6.0.6 on 2026-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField(unique=True)),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('session', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
        ),
    ]
