# Generated by Django 6.0.6 on 2026-07-19 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number.', regex='^01[3-9]\\d{8}$')])),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number.', regex='^01[3-9]\\d{8}$')])),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.bloodgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.session')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.studentclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'student_class', 'section', 'department', 'roll'), name='unique_student_roll')],
            },
        ),
    ]
